# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dzheng/workspace/cmdline

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dzheng/workspace/cmdline

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dzheng/workspace/cmdline/CMakeFiles /home/dzheng/workspace/cmdline//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dzheng/workspace/cmdline/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cmdline

# Build rule for target.
cmdline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmdline
.PHONY : cmdline

# fast build rule for target.
cmdline/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdline.dir/build.make CMakeFiles/cmdline.dir/build
.PHONY : cmdline/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named example_constexpr

# Build rule for target.
example_constexpr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_constexpr
.PHONY : example_constexpr

# fast build rule for target.
example_constexpr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_constexpr.dir/build.make CMakeFiles/example_constexpr.dir/build
.PHONY : example_constexpr/fast

#=============================================================================
# Target rules for targets named constexpr_test

# Build rule for target.
constexpr_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 constexpr_test
.PHONY : constexpr_test

# fast build rule for target.
constexpr_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/constexpr_test.dir/build.make CMakeFiles/constexpr_test.dir/build
.PHONY : constexpr_test/fast

#=============================================================================
# Target rules for targets named test_lambda_types

# Build rule for target.
test_lambda_types: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lambda_types
.PHONY : test_lambda_types

# fast build rule for target.
test_lambda_types/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lambda_types.dir/build.make CMakeFiles/test_lambda_types.dir/build
.PHONY : test_lambda_types/fast

#=============================================================================
# Target rules for targets named test_parse_invoke

# Build rule for target.
test_parse_invoke: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_parse_invoke
.PHONY : test_parse_invoke

# fast build rule for target.
test_parse_invoke/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parse_invoke.dir/build.make CMakeFiles/test_parse_invoke.dir/build
.PHONY : test_parse_invoke/fast

#=============================================================================
# Target rules for targets named test_typed_options

# Build rule for target.
test_typed_options: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_typed_options
.PHONY : test_typed_options

# fast build rule for target.
test_typed_options/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_typed_options.dir/build.make CMakeFiles/test_typed_options.dir/build
.PHONY : test_typed_options/fast

#=============================================================================
# Target rules for targets named test_variadic_groups

# Build rule for target.
test_variadic_groups: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_variadic_groups
.PHONY : test_variadic_groups

# fast build rule for target.
test_variadic_groups/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_variadic_groups.dir/build.make CMakeFiles/test_variadic_groups.dir/build
.PHONY : test_variadic_groups/fast

#=============================================================================
# Target rules for targets named test_int_range

# Build rule for target.
test_int_range: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_int_range
.PHONY : test_int_range

# fast build rule for target.
test_int_range/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_int_range.dir/build.make CMakeFiles/test_int_range.dir/build
.PHONY : test_int_range/fast

#=============================================================================
# Target rules for targets named test_array_range

# Build rule for target.
test_array_range: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_array_range
.PHONY : test_array_range

# fast build rule for target.
test_array_range/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array_range.dir/build.make CMakeFiles/test_array_range.dir/build
.PHONY : test_array_range/fast

#=============================================================================
# Target rules for targets named test_option_matching

# Build rule for target.
test_option_matching: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_option_matching
.PHONY : test_option_matching

# fast build rule for target.
test_option_matching/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_option_matching.dir/build.make CMakeFiles/test_option_matching.dir/build
.PHONY : test_option_matching/fast

#=============================================================================
# Target rules for targets named test_subcommands

# Build rule for target.
test_subcommands: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_subcommands
.PHONY : test_subcommands

# fast build rule for target.
test_subcommands/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_subcommands.dir/build.make CMakeFiles/test_subcommands.dir/build
.PHONY : test_subcommands/fast

#=============================================================================
# Target rules for targets named test_mode_manager

# Build rule for target.
test_mode_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mode_manager
.PHONY : test_mode_manager

# fast build rule for target.
test_mode_manager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mode_manager.dir/build.make CMakeFiles/test_mode_manager.dir/build
.PHONY : test_mode_manager/fast

#=============================================================================
# Target rules for targets named test_default_values

# Build rule for target.
test_default_values: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_default_values
.PHONY : test_default_values

# fast build rule for target.
test_default_values/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_default_values.dir/build.make CMakeFiles/test_default_values.dir/build
.PHONY : test_default_values/fast

#=============================================================================
# Target rules for targets named test_option_value

# Build rule for target.
test_option_value: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_option_value
.PHONY : test_option_value

# fast build rule for target.
test_option_value/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_option_value.dir/build.make CMakeFiles/test_option_value.dir/build
.PHONY : test_option_value/fast

cmdline.o: cmdline.cpp.o
.PHONY : cmdline.o

# target to build an object file
cmdline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdline.dir/build.make CMakeFiles/cmdline.dir/cmdline.cpp.o
.PHONY : cmdline.cpp.o

cmdline.i: cmdline.cpp.i
.PHONY : cmdline.i

# target to preprocess a source file
cmdline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdline.dir/build.make CMakeFiles/cmdline.dir/cmdline.cpp.i
.PHONY : cmdline.cpp.i

cmdline.s: cmdline.cpp.s
.PHONY : cmdline.s

# target to generate assembly for a file
cmdline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdline.dir/build.make CMakeFiles/cmdline.dir/cmdline.cpp.s
.PHONY : cmdline.cpp.s

constexpr_test.o: constexpr_test.cpp.o
.PHONY : constexpr_test.o

# target to build an object file
constexpr_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/constexpr_test.dir/build.make CMakeFiles/constexpr_test.dir/constexpr_test.cpp.o
.PHONY : constexpr_test.cpp.o

constexpr_test.i: constexpr_test.cpp.i
.PHONY : constexpr_test.i

# target to preprocess a source file
constexpr_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/constexpr_test.dir/build.make CMakeFiles/constexpr_test.dir/constexpr_test.cpp.i
.PHONY : constexpr_test.cpp.i

constexpr_test.s: constexpr_test.cpp.s
.PHONY : constexpr_test.s

# target to generate assembly for a file
constexpr_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/constexpr_test.dir/build.make CMakeFiles/constexpr_test.dir/constexpr_test.cpp.s
.PHONY : constexpr_test.cpp.s

example.o: example.cpp.o
.PHONY : example.o

# target to build an object file
example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.cpp.o
.PHONY : example.cpp.o

example.i: example.cpp.i
.PHONY : example.i

# target to preprocess a source file
example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.cpp.i
.PHONY : example.cpp.i

example.s: example.cpp.s
.PHONY : example.s

# target to generate assembly for a file
example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.cpp.s
.PHONY : example.cpp.s

example_constexpr.o: example_constexpr.cpp.o
.PHONY : example_constexpr.o

# target to build an object file
example_constexpr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_constexpr.dir/build.make CMakeFiles/example_constexpr.dir/example_constexpr.cpp.o
.PHONY : example_constexpr.cpp.o

example_constexpr.i: example_constexpr.cpp.i
.PHONY : example_constexpr.i

# target to preprocess a source file
example_constexpr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_constexpr.dir/build.make CMakeFiles/example_constexpr.dir/example_constexpr.cpp.i
.PHONY : example_constexpr.cpp.i

example_constexpr.s: example_constexpr.cpp.s
.PHONY : example_constexpr.s

# target to generate assembly for a file
example_constexpr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_constexpr.dir/build.make CMakeFiles/example_constexpr.dir/example_constexpr.cpp.s
.PHONY : example_constexpr.cpp.s

test_array_range.o: test_array_range.cpp.o
.PHONY : test_array_range.o

# target to build an object file
test_array_range.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array_range.dir/build.make CMakeFiles/test_array_range.dir/test_array_range.cpp.o
.PHONY : test_array_range.cpp.o

test_array_range.i: test_array_range.cpp.i
.PHONY : test_array_range.i

# target to preprocess a source file
test_array_range.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array_range.dir/build.make CMakeFiles/test_array_range.dir/test_array_range.cpp.i
.PHONY : test_array_range.cpp.i

test_array_range.s: test_array_range.cpp.s
.PHONY : test_array_range.s

# target to generate assembly for a file
test_array_range.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array_range.dir/build.make CMakeFiles/test_array_range.dir/test_array_range.cpp.s
.PHONY : test_array_range.cpp.s

test_default_values.o: test_default_values.cpp.o
.PHONY : test_default_values.o

# target to build an object file
test_default_values.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_default_values.dir/build.make CMakeFiles/test_default_values.dir/test_default_values.cpp.o
.PHONY : test_default_values.cpp.o

test_default_values.i: test_default_values.cpp.i
.PHONY : test_default_values.i

# target to preprocess a source file
test_default_values.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_default_values.dir/build.make CMakeFiles/test_default_values.dir/test_default_values.cpp.i
.PHONY : test_default_values.cpp.i

test_default_values.s: test_default_values.cpp.s
.PHONY : test_default_values.s

# target to generate assembly for a file
test_default_values.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_default_values.dir/build.make CMakeFiles/test_default_values.dir/test_default_values.cpp.s
.PHONY : test_default_values.cpp.s

test_int_range.o: test_int_range.cpp.o
.PHONY : test_int_range.o

# target to build an object file
test_int_range.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_int_range.dir/build.make CMakeFiles/test_int_range.dir/test_int_range.cpp.o
.PHONY : test_int_range.cpp.o

test_int_range.i: test_int_range.cpp.i
.PHONY : test_int_range.i

# target to preprocess a source file
test_int_range.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_int_range.dir/build.make CMakeFiles/test_int_range.dir/test_int_range.cpp.i
.PHONY : test_int_range.cpp.i

test_int_range.s: test_int_range.cpp.s
.PHONY : test_int_range.s

# target to generate assembly for a file
test_int_range.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_int_range.dir/build.make CMakeFiles/test_int_range.dir/test_int_range.cpp.s
.PHONY : test_int_range.cpp.s

test_lambda_types.o: test_lambda_types.cpp.o
.PHONY : test_lambda_types.o

# target to build an object file
test_lambda_types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lambda_types.dir/build.make CMakeFiles/test_lambda_types.dir/test_lambda_types.cpp.o
.PHONY : test_lambda_types.cpp.o

test_lambda_types.i: test_lambda_types.cpp.i
.PHONY : test_lambda_types.i

# target to preprocess a source file
test_lambda_types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lambda_types.dir/build.make CMakeFiles/test_lambda_types.dir/test_lambda_types.cpp.i
.PHONY : test_lambda_types.cpp.i

test_lambda_types.s: test_lambda_types.cpp.s
.PHONY : test_lambda_types.s

# target to generate assembly for a file
test_lambda_types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lambda_types.dir/build.make CMakeFiles/test_lambda_types.dir/test_lambda_types.cpp.s
.PHONY : test_lambda_types.cpp.s

test_mode_manager.o: test_mode_manager.cpp.o
.PHONY : test_mode_manager.o

# target to build an object file
test_mode_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mode_manager.dir/build.make CMakeFiles/test_mode_manager.dir/test_mode_manager.cpp.o
.PHONY : test_mode_manager.cpp.o

test_mode_manager.i: test_mode_manager.cpp.i
.PHONY : test_mode_manager.i

# target to preprocess a source file
test_mode_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mode_manager.dir/build.make CMakeFiles/test_mode_manager.dir/test_mode_manager.cpp.i
.PHONY : test_mode_manager.cpp.i

test_mode_manager.s: test_mode_manager.cpp.s
.PHONY : test_mode_manager.s

# target to generate assembly for a file
test_mode_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mode_manager.dir/build.make CMakeFiles/test_mode_manager.dir/test_mode_manager.cpp.s
.PHONY : test_mode_manager.cpp.s

test_option_matching.o: test_option_matching.cpp.o
.PHONY : test_option_matching.o

# target to build an object file
test_option_matching.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_option_matching.dir/build.make CMakeFiles/test_option_matching.dir/test_option_matching.cpp.o
.PHONY : test_option_matching.cpp.o

test_option_matching.i: test_option_matching.cpp.i
.PHONY : test_option_matching.i

# target to preprocess a source file
test_option_matching.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_option_matching.dir/build.make CMakeFiles/test_option_matching.dir/test_option_matching.cpp.i
.PHONY : test_option_matching.cpp.i

test_option_matching.s: test_option_matching.cpp.s
.PHONY : test_option_matching.s

# target to generate assembly for a file
test_option_matching.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_option_matching.dir/build.make CMakeFiles/test_option_matching.dir/test_option_matching.cpp.s
.PHONY : test_option_matching.cpp.s

test_option_value.o: test_option_value.cpp.o
.PHONY : test_option_value.o

# target to build an object file
test_option_value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_option_value.dir/build.make CMakeFiles/test_option_value.dir/test_option_value.cpp.o
.PHONY : test_option_value.cpp.o

test_option_value.i: test_option_value.cpp.i
.PHONY : test_option_value.i

# target to preprocess a source file
test_option_value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_option_value.dir/build.make CMakeFiles/test_option_value.dir/test_option_value.cpp.i
.PHONY : test_option_value.cpp.i

test_option_value.s: test_option_value.cpp.s
.PHONY : test_option_value.s

# target to generate assembly for a file
test_option_value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_option_value.dir/build.make CMakeFiles/test_option_value.dir/test_option_value.cpp.s
.PHONY : test_option_value.cpp.s

test_parse_invoke.o: test_parse_invoke.cpp.o
.PHONY : test_parse_invoke.o

# target to build an object file
test_parse_invoke.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parse_invoke.dir/build.make CMakeFiles/test_parse_invoke.dir/test_parse_invoke.cpp.o
.PHONY : test_parse_invoke.cpp.o

test_parse_invoke.i: test_parse_invoke.cpp.i
.PHONY : test_parse_invoke.i

# target to preprocess a source file
test_parse_invoke.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parse_invoke.dir/build.make CMakeFiles/test_parse_invoke.dir/test_parse_invoke.cpp.i
.PHONY : test_parse_invoke.cpp.i

test_parse_invoke.s: test_parse_invoke.cpp.s
.PHONY : test_parse_invoke.s

# target to generate assembly for a file
test_parse_invoke.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parse_invoke.dir/build.make CMakeFiles/test_parse_invoke.dir/test_parse_invoke.cpp.s
.PHONY : test_parse_invoke.cpp.s

test_subcommands.o: test_subcommands.cpp.o
.PHONY : test_subcommands.o

# target to build an object file
test_subcommands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_subcommands.dir/build.make CMakeFiles/test_subcommands.dir/test_subcommands.cpp.o
.PHONY : test_subcommands.cpp.o

test_subcommands.i: test_subcommands.cpp.i
.PHONY : test_subcommands.i

# target to preprocess a source file
test_subcommands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_subcommands.dir/build.make CMakeFiles/test_subcommands.dir/test_subcommands.cpp.i
.PHONY : test_subcommands.cpp.i

test_subcommands.s: test_subcommands.cpp.s
.PHONY : test_subcommands.s

# target to generate assembly for a file
test_subcommands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_subcommands.dir/build.make CMakeFiles/test_subcommands.dir/test_subcommands.cpp.s
.PHONY : test_subcommands.cpp.s

test_typed_options.o: test_typed_options.cpp.o
.PHONY : test_typed_options.o

# target to build an object file
test_typed_options.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_typed_options.dir/build.make CMakeFiles/test_typed_options.dir/test_typed_options.cpp.o
.PHONY : test_typed_options.cpp.o

test_typed_options.i: test_typed_options.cpp.i
.PHONY : test_typed_options.i

# target to preprocess a source file
test_typed_options.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_typed_options.dir/build.make CMakeFiles/test_typed_options.dir/test_typed_options.cpp.i
.PHONY : test_typed_options.cpp.i

test_typed_options.s: test_typed_options.cpp.s
.PHONY : test_typed_options.s

# target to generate assembly for a file
test_typed_options.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_typed_options.dir/build.make CMakeFiles/test_typed_options.dir/test_typed_options.cpp.s
.PHONY : test_typed_options.cpp.s

test_variadic_groups.o: test_variadic_groups.cpp.o
.PHONY : test_variadic_groups.o

# target to build an object file
test_variadic_groups.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_variadic_groups.dir/build.make CMakeFiles/test_variadic_groups.dir/test_variadic_groups.cpp.o
.PHONY : test_variadic_groups.cpp.o

test_variadic_groups.i: test_variadic_groups.cpp.i
.PHONY : test_variadic_groups.i

# target to preprocess a source file
test_variadic_groups.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_variadic_groups.dir/build.make CMakeFiles/test_variadic_groups.dir/test_variadic_groups.cpp.i
.PHONY : test_variadic_groups.cpp.i

test_variadic_groups.s: test_variadic_groups.cpp.s
.PHONY : test_variadic_groups.s

# target to generate assembly for a file
test_variadic_groups.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_variadic_groups.dir/build.make CMakeFiles/test_variadic_groups.dir/test_variadic_groups.cpp.s
.PHONY : test_variadic_groups.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cmdline"
	@echo "... constexpr_test"
	@echo "... example"
	@echo "... example_constexpr"
	@echo "... test_array_range"
	@echo "... test_default_values"
	@echo "... test_int_range"
	@echo "... test_lambda_types"
	@echo "... test_mode_manager"
	@echo "... test_option_matching"
	@echo "... test_option_value"
	@echo "... test_parse_invoke"
	@echo "... test_subcommands"
	@echo "... test_typed_options"
	@echo "... test_variadic_groups"
	@echo "... cmdline.o"
	@echo "... cmdline.i"
	@echo "... cmdline.s"
	@echo "... constexpr_test.o"
	@echo "... constexpr_test.i"
	@echo "... constexpr_test.s"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
	@echo "... example_constexpr.o"
	@echo "... example_constexpr.i"
	@echo "... example_constexpr.s"
	@echo "... test_array_range.o"
	@echo "... test_array_range.i"
	@echo "... test_array_range.s"
	@echo "... test_default_values.o"
	@echo "... test_default_values.i"
	@echo "... test_default_values.s"
	@echo "... test_int_range.o"
	@echo "... test_int_range.i"
	@echo "... test_int_range.s"
	@echo "... test_lambda_types.o"
	@echo "... test_lambda_types.i"
	@echo "... test_lambda_types.s"
	@echo "... test_mode_manager.o"
	@echo "... test_mode_manager.i"
	@echo "... test_mode_manager.s"
	@echo "... test_option_matching.o"
	@echo "... test_option_matching.i"
	@echo "... test_option_matching.s"
	@echo "... test_option_value.o"
	@echo "... test_option_value.i"
	@echo "... test_option_value.s"
	@echo "... test_parse_invoke.o"
	@echo "... test_parse_invoke.i"
	@echo "... test_parse_invoke.s"
	@echo "... test_subcommands.o"
	@echo "... test_subcommands.i"
	@echo "... test_subcommands.s"
	@echo "... test_typed_options.o"
	@echo "... test_typed_options.i"
	@echo "... test_typed_options.s"
	@echo "... test_variadic_groups.o"
	@echo "... test_variadic_groups.i"
	@echo "... test_variadic_groups.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

